### ISSUE TITLE
Handsfree-ify Google Stadia

### ISSUE THREAD

**Issue by MIDIBlocks** [MIDIBlocks/handsfree#103]
- [x] Update background script with handsfree.js config of current tab...both on page load and tab focus
- [x] Add an event to update Handsfree in the background script (for example, for switching models)
- [ ] Use Weboji to move mouse
- [ ] Emit keys with various gestures
- [ ] Get Everspace working handsfree

**Comment by ozramos** [comment]
Closing all demos to just focus on maintenance for now
