### ISSUE TITLE
Module fails to load in my create-react-app project

### ISSUE THREAD

**Issue by blurymind** [MIDIBlocks/handsfree#110]
I get this
```
./node_modules/handsfree/src/handsfree.js 321:36
Module parse failed: Unexpected token (321:36)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|
|     Object.keys(this.config.plugin).forEach(plugin => {
>       if (typeof this.config.plugin?.[plugin]?.enabled === 'boolean' && this.config.plugin[plugin].enabled) {
|         this.plugin[plugin].enable();
|       }

```

any ideas?

**Comment by MIDIBlocks** [comment]
Oh thanks for creating this issue! I've been using the optional chaining operator ?. as a shortcut when writing out if statements, and I didn't think about whether ?. is widely supported yet. It looks like optional chaining is still a fairly new feature so I'm going to go through and get rid of these but it may take me a few days to get to.

However in the mean time you can try adding optional chaining to your Babel. Are you using React < 3? I'm not familiar with React myself but depending on your version of React this link may help: https://medium.com/@adostes/enabling-optional-chaining-in-a-create-react-app-a9f626a515d9

**Comment by blurymind** [comment]
I think the typescript transpiler probably doesnt support optional chaining by default and its why it fails. I have a way around this which is to include the minified module in the public folder and access it via the global object, but it is not pretty

**Comment by MIDIBlocks** [comment]
I'm glad to hear you were able to work around it for now! I totally agree and in fact not only should it work across frameworks but environments too without any config (like within Node or Electron).

It'll take a little more iteration to get there, but I appreciate you raising these points!

**Comment by Beherit79** [comment]
Yo, just to provide feedback.

I had an old React application bundled with webpack 3 on which I wanted to add Handsfree (hands/gesture).  
I had to upgrade to webpack 5 and add "@babel/plugin-proposal-optional-chaining": "^7.13.8" as devDep in package.json + .babelrc

**Comment by blurymind** [comment]
well ideally I think it would be great if the library itself gets transpilled in a way that allows it to be used without having to set up extra stuff in the projects where it is used :)

**Comment by MIDIBlocks** [comment]
Oh...I didn't think about transpiling thank you for mentioning that! I was so intimidated by this issue thinking I would have to rewrite the library (I use optional chaining everywhere) but I didn't realize that I can just keep the code and transpile. Right now I'm just using Rollup, so I think this should be easy to do

I will do this either tonight or tomorrow. Thanks for being patient with me 🙏

**Comment by MIDIBlocks** [comment]
Okay should be all set! You'll need to `npm update handsfree` to get the latest version. I'm not familiar with React so I don't know what best practices are, but I created a CodeSandbox to demonstrate it working: https://codesandbox.io/s/create-react-app-handsfree-s9xx4?file=/src/index.js

**Comment by Beherit79** [comment]
Thank you Oz, it's works.
