### ISSUE TITLE
Allow handsfree to run in the background (eg. electron)

### ISSUE THREAD

**Issue by GDur** [MIDIBlocks/handsfree#111]
When I tried to use this library using electron, it only worked when the window wasn't hidden.

The reason seems to be that it is using the requestAnimationFrame method.

I would be nice to have a "force-loop" option, to force it to run in the background eg. using the setInterval method.

**Comment by MIDIBlocks** [comment]
Oh thank you for this issue! I've been thinking about this a lot recently as well and the best way to approach this, but I wonder if you'll still run into issues with `setInterval`? Some quick research shows that the problem might just be that electron/browsers throttle inactive contexts and my feeling is that even if I switch to setInterval it will still get throttled.

I haven't used Electron yet, but if your setup/requirements allow maybe you could try disabling `backgroundThrottling` which is enabled by default: https://www.electronjs.org/docs/api/browser-window#page-visibility

I'll look into providing a "force-loop" option with setInterval, that's a great idea! I have started on a way to forcefully run the loop yourself with `[handsfree.runPlugins()](https://handsfree.js.org/ref/method/runPlugins.html)` which I use heavily in browser extensions, but you would still need to create your own setInterval loop which I suspect will still get throttled.

Let me know if that helps and if not I'll look into this more!

**Comment by GDur** [comment]
Thank you so much for your reply.


> maybe you could try disabling `backgroundThrottling`

This works great!  (I tried to find such an option but couldn't) 🚀  

> but I wonder if you'll still run into issues with `setInterval`

I adjusted the code using the `setInterval` method and it worked in general but it was almost impossible to reload the electron window. So your guess that this method would lead to issues seems to be true. 


> I have started on a way to forcefully run the loop yourself with [handsfree.runPlugins()](https://handsfree.js.org/ref/method/runPlugins.html)

Very interesting! I will take a look at this. Maybe this is even better than the `backgroundThrottling` option.


Good job so far. You can close this issue imo👍
