### ISSUE TITLE
Using throttle method to improve performance 

### ISSUE THREAD

**Issue by Omodaka9375** [MIDIBlocks/handsfree#121]
I use handsfreejs to train my custom CNN/RNN classifier on top of mediapipe models in the browser.
I would eventually like to run it on my Raspberry Pi 4 so I played around with `throttle()` method for performance improvement.

I use it to reduce the calls to model like so:
```
handsfree.model.hands.getData = handsfree.throttle(handsfree.model.hands.getData, 1000 / targetFPS)
```
but this doesn't reflect the FPS property so ` onFrame (data) ` is still getting called every frame but it just passes frame duplicates until model is run next time.

This feature would be proper if throttling would also limit respectively the number of the sampled frames, so that data that comes out of 'onFrame()' callback is always reflected correctly. Otherwise, this throttling method is only affecting the calls to the model, but maybe it should also handle frame duplicates in that case.

**Comment by MIDIBlocks** [comment]
Hi thanks for starting this issue, this is an interesting case! Throttling models individually isn't easily possible right now (and to be honest I'm not sure what the best way to approach this would be yet) but you can throttle the actual loop. Here's what that would look like:

```js
handsfree.loop = handsfree.throttle(handsfree.loop, 1000 / targetFPS)
```

Also this is a minor point, but I just learned that I got the documentation for throttle wrong. `handsfree.throttle` is now just an alias to lodash.throttle and can receive a few extra arguments: https://lodash.com/docs/4.17.15#throttle

## Tasks
- [ ] Fix handsfree.throttle documentation

**Comment by Omodaka9375** [comment]
'handsfree.loop = handsfree.throttle(handsfree.loop, 1000 / targetFPS)'

Throttling the main loop did the trick, There are no duplicates and sampling can be set via targetFPS safely.

Thanks @MIDIBlocks
