### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by RedmindTechnologies** [MIDIBlocks/handsfree#122]
Could anybody suggest how to host this in firebase platform

**Comment by MIDIBlocks** [comment]
Hi, do you mean hosting through Firebase Hosting? If so, then you should be able to just follow [their quickstart guide](https://firebase.google.com/docs/hosting/quickstart) as there is nothing special about Handsfree.js (it's just another library). Depending on how you're building your app (Vue, React, vanilla JS, etc) then you may need to eject the models from `/node_modules/` into your public folder which you can do with:

```bash
# ON WINDOWS
xcopy /e node_modules\handsfree\build\lib PUBLIC
# EVERYWHERE ELSE
cp -r node_modules/handsfree/build/lib/* PUBLIC
```

I suspect you already tried this though, if so can you let me know what you're getting stuck on? I've used Handsfree.js on Firebase many times before and can definitely help with this

**Comment by MIDIBlocks** [comment]
Closing for now since I never got a response, but please don't hesitate to reopen!
