### ISSUE TITLE
As a user, I want to implement eye tracking

### ISSUE THREAD

**Issue by labofoz** [MIDIBlocks/handsfree#3]
Let's implement [WebGazer](https://webgazer.cs.brown.edu/)

Request:
- https://twitter.com/fr3ddy/status/1192209578722770945
- https://twitter.com/MIDIBlocks/status/1318770324121427969

**Comment by delebash** [comment]
If you implement this I would be very interested in how you do it.  The holistic mediapipe app has everything but iris tracking already integrated.

**Comment by MIDIBlocks** [comment]
For sure! I plan on implementing the MediaPipe [iris model](https://google.github.io/mediapipe/solutions/iris.html), but I'm holding off a bit more as it doesn't look like it's been officially released by the MediaPipe team for the web yet (there is this [web demo though](https://google.github.io/mediapipe/#mediapipe-on-the-web))

**Comment by Beherit79** [comment]
This would be great ! 
realeye.io implemented WebGazer JS (+ some modifications). There is a live demo, it works really well.

Keep it up ! Your job is awesome ! :)

**Comment by ozramos** [comment]
Closing and moving this to #150 with MediaPipe Iris: https://google.github.io/mediapipe/solutions/iris.html
