### ISSUE TITLE
Handsfree cannot be imported as standard node module

### ISSUE THREAD

**Issue by mattrossman** [MIDIBlocks/handsfree#51]
According to `package.json`, the "main" script should be in `dist/index.js`. However, the build script outputs it to `dist/handsfree.js`.

As a result, writing
```javascript
const Handsfree = require('handsfree')
```
produces an error.

I'm really not sure how we're expected to use this as a node module. I tried explicitly requiring it as:
```javascript
const Handsfree = require('handsfree/dist/handsfree')
```
But this makes my bundler (parcel) complain:
```
Target "main" declares an output file path of "index.js" which does not match the compiled bundle type "html"
```

The documented example of
```javascript
import Handsfree from 'handsfree`
```
does not work either. Am I missing something?

**Comment by MIDIBlocks** [comment]
Hi! I'm really sorry for taking half a year to respond.

Something to do with Parcel (the package manager I was using) broke right around the time that I paused working on this and I didn't catch it until now. I'm now using Rollup.

I've added new instructions to the readme on how to [include via npm](https://github.com/MIDIBlocks/handsfree#npm-quickstart). I'm still learning Rollup tho so there are a few extra steps you need to take. In short:

I switched over from Parcel to Rollup for package management and am still new to it. For now, a little extra setup is needed when installing through npm:

- Install with: `npm i handsfree`
- Copy this project's `/public/assets` folder into your own projects public folder (this makes the computer vision models accessible to your app)
- When instantiating `Handsfree`, set the `assetsPath` property:

```js
import Handsfree from 'handsfree'
const handsfree = new Handsfree({
  weboji: true,
  assetsPath: document.location.origin + '/assets/'
})
```

---

Closing for now as this is a fairly old issue (again I apologize), please let me know if you have any questions
