### ISSUE TITLE
Cursor

### ISSUE THREAD

**Issue by timo-cmd** [MIDIBlocks/handsfree#52]
Hey,

How to change the cursor speed?

**Comment by MIDIBlocks** [comment]
Hi! Sorry for the delay, I had paused working on this project but am picking it back up!

I still need to redo documentation, but for now try something like this: [https://glitch.com/edit/#!/handsfreejs?path=demo%2Fadjust-pointer-sensitivity.html%3A43%3A14](https://glitch.com/edit/#!/handsfreejs?path=demo%2Fadjust-pointer-sensitivity.html%3A43%3A14)

```
    // Create a new instance. Use one instance for each camera
    const handsfree = new Handsfree({
      weboji: true,

      // Override the "weboji.pointer" plugin's default speed
      plugin: {
        facePointer: {
          speed: {
            x: 0.5,
            y: 0.5
          },
          offset: {
            x: 0,
            y: window.outerHeight / 2
          }
        }
      }
    })
```
