### ISSUE TITLE
Is it possible to record with handsfree?

### ISSUE THREAD

**Issue by Obinnabii** [MIDIBlocks/handsfree#56]
Hi, I'm trying to use handsfree and I need to record the screen and camera for my application. I see that you guys do a similar thing with your tutorials. Is there a resource that could help me with this?

**Comment by MIDIBlocks** [comment]
Hi! Sorry for the delay I'm just picking this project back up and will provide new documentation over the next few days

You can enable the camera with:

```js
handsfree = new Handsfree({
  weboji: true,
  feedback: {enabled: true}
})
```

This will place a canvas with your webcam feed into the dom, which you can style. The markup looks like:

```html
<div class="handsfree-feedback">
  <canvas class="handsfree-canvas" id="handsfree-canvas-2" width="320" height="240"></canvas>
  <video playsinline="true" class="handsfree-video" id="handsfree-video-2" width="640" height="480" data-vscid="ohn96w6wf"></video>
  <canvas class="handsfree-debug" id="handsfree-debug-2" width="640" height="480"></canvas>
</div>
```

**Comment by Obinnabii** [comment]
Thank you!

**Comment by Obinnabii** [comment]
I also used the ```handsfree.debugger``` parameter to get the debugger stream.
