### ISSUE TITLE
Is it possible to get a confidence level or a measure for face detection? 

### ISSUE THREAD

**Issue by DavidNTompkins** [MIDIBlocks/handsfree#58]
First off - this tool is super cool, thank you for building it. I'm incorporating it in a page where I want something to be controlled (via rotation) if a face is present, but not if the face is not present. Is there a way to get the value of JEEFACETRANSFERAPI.is_detected() or similar? A % confidence would be sick, but a boolean would also work. 

Thanks again

**Comment by MIDIBlocks** [comment]
Hi thank you so much for giving this a try, and also I will have updated documentation soon!

Everything is exposed under `handsfree.weboji.api`, so in your case you would do: `handsfree.weboji.api.is_detected()`

If you need to check this on every webcam frame, I would create a "plugin". Something like:

```js
handsfree.use('myPluginName', {
  // weboji here is just destructured from `handsfree.weboji`, this is to make typing easier
  onFrame ({weboji}) {
    // do stuff when detected
    if (weboji.api.is_detected()) {
       // do stuff when head is rotated along z-axis more than someValue in Radians
       if (weboji.data.rotation[2] > someValue) {
       }
    }
  }
})
```

Note that this library is a bit old now (Spring was the last time that I made any significant changes). However, I'll be updating all the models in the next few days...there should be no breaking changes, just faster and newer models.

**Comment by DavidNTompkins** [comment]
Thanks! I ran into a couple issues trying to implement that (weboji was undefined - very likely an error on my side), but found that I could call window.JEEFACETRANSFERAPI.is_detected(); which seems to be effectively the same.

Thanks again for the help and tool!
