### ISSUE TITLE
Loading scripts from CDN is not working

### ISSUE THREAD

**Issue by benjaminadolph** [MIDIBlocks/handsfree#64]
Hi! I´m a student and I just started experimenting with handsfree.js - it´s awesome. 
I just updated the CDN links in my project to v7.1.0 and when I started my local server I got this error in Chrome:
**GET http://127.0.0.1:35729/livereload.js?snipver=1 net::ERR_CONNECTION_REFUSED - handsfree.js:2** 

When I tried to use the provided demo on the starting page of your new documentation I got this error: 
**Invalid property immediate set to true Missing plugin? gsap.registerPlugin() - 4.5020b82c.js:10**

Any help would be greatly appreciated!

Cheers,
Benjamin

**Comment by MIDIBlocks** [comment]
Hi thanks for reporting this, I was not aware that CDN had been broken all this time! The new CDN urls are 7.2.11:

```html
<head>
  <!-- Include Handsfree.js -->
  <link rel="stylesheet" href="https://unpkg.com/handsfree@7.2.11/build/lib/assets/handsfree.css" />
  <script src="https://unpkg.com/handsfree@7.2.11/build/lib/handsfree.js"></script>
</head>

<!-- Instantiate and start it -->
<body>
  <script>
    const handsfree = new Handsfree({face: true})
    handsfree.start()
  </script>
</body>
```

I've also started updating the docs at https://handsfree.js.org, but it's still a bit behind. I should have caught up with documentation, including a few starter examples, by Dec 1. If you don't require all the helper methods, quick setup, or plugins (face pointer, hand pointer, etc), then you can use the models directly:

- Face Tracking through [Weboji](https://github.com/jeeliz/jeelizWeboji)
- Hand Tracking through [Handpose](https://github.com/tensorflow/tfjs-models/tree/master/handpose)
- Pose Estimation through [PoseNet](https://github.com/tensorflow/tfjs-models/tree/master/posenet)

Also note, that each of the APIs for each of these models are available through `handsfree.weboji.api`, `handsfree.handpose.api`, and `handsfree.posenet.api` when those models are loaded. This helps you use Handsfree.js to simply inject these models into your app.

I'll have 100% documentation coverage, a forum, and a Slack available on Dec 1 but until then I'd be happy to help you with anything else or direct you to other resources that you can try. Thanks again for bringing this up!

**Comment by benjaminadolph** [comment]
No problem, thanks for your quick response and the additional information! I will gladly come back to your offer if further problems should arise. But with the new links everything is working so far.
