### ISSUE TITLE
Handsfree not loading with node.js

### ISSUE THREAD

**Issue by Obinnabii** [MIDIBlocks/handsfree#74]
I get this error when I try to require/import handsfree

```console
/node_modules/handsfree/src/handsfree.js:2
import merge from 'lodash/merge'
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

It seems to be coming from the npm handsfree module

**Comment by Obinnabii** [comment]
I saw that you talked about this in https://github.com/MIDIBlocks/handsfree/issues/67#issuecomment-747572173

**Comment by MIDIBlocks** [comment]
How are you including the library? If you're including it by `<script>` tag you may need to add `type=module` to it:

```js
<script type="module" src="/node_modules/handsfree/src/handsfree.js"></script>
```

I haven't tried to include it straight from the node_modules from a script yet but that should work. It may just work out of the box, but if you get an error about not being able to find the dependencies then you'll also need to extract move the dependencies out of `/node_modules/handsfree/build/lib/assets/` up into where your other images/files are and tell Handsfree to look there by setting the `assetsPath` in config (but I don't think you'll need to do this):

```js
handsfree = new Handsfree({face: true, assetsPath: '/path/to/assets/`})
````

**Comment by MIDIBlocks** [comment]
Oh and if you're including it in a script, it may be better to include this one instead:

```js
<script src="/node_modules/handsfree/build/lib/handsfree.js"></script>
```

Then you shouldn't need to add the `type=module`

**Comment by Obinnabii** [comment]
I was trying to include it in a node script without using a webpage. 
But I guess I could use it this way instead.

**Comment by MIDIBlocks** [comment]
Oh I'm not sure if it will work without a server, you may have to use the CDN: https://handsfree.js.org/#through-cdn

This is a JavaScript limitation due to the way the files are loaded after the page loads (to keep filesize small). I'll smush everything together in the next release so that you can use it without a server. The filesize will be huge but maybe that won't be a big issue if using locally

**Comment by MIDIBlocks** [comment]
Oh sorry I think I completely misunderstood the question 😅

If you're still working on this I'd love to help, could you describe your environment if you are? I don't really know Node well but I may be able to help (I'm more of a front end dev that just happens to use it to bundle stuff etc)

It used to be that some of the models I'm using required a Canvas context which at the time wouldn't work even with browserless polyfills but that may have changed by now.

**Comment by Obinnabii** [comment]
No problem. I was working on a package/platform to analyze facial movements in research videos using Handsfree.js. I managed to create a local server where I can log head tilts, roll, and position. The project is currently on hiatus and will probably pick up again in the Spring. 

My initial plan for the package was to feed in folders of video files on the command line and have the program analyze them all and return frame by frame CSV analysis files. 

The current implementation plays a video on a webpage and compiles a CSV based on the given video.

**Comment by MIDIBlocks** [comment]
Oh I see thanks for explaining the use case! Someone else has requested something similar so I'll investigate this a bit further over the next few weeks and hopefully have something working for when you return.

I'm going to close this issue for now as I don't think this is possible at the moment but please feel free to reopen or start a new one :)
